# Generated by Django 3.2.12 on 2022-06-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del Cliente')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=10, verbose_name='rut')),
                ('direccion', models.CharField(max_length=30, verbose_name='direccion')),
                ('telefono', models.CharField(max_length=15, verbose_name='telefono')),
            ],
        ),
    ]
