# Generated by Django 3.2.12 on 2022-06-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default=123, upload_to='productos', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
